# Generated by Django 4.1 on 2022-09-10 07:53

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone
import user.manager


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('auth', '0012_alter_user_first_name_max_length'),
    ]

    operations = [
        migrations.CreateModel(
            name='User',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('password', models.CharField(max_length=128, verbose_name='password')),
                ('last_login', models.DateTimeField(blank=True, null=True, verbose_name='last login')),
                ('is_superuser', models.BooleanField(default=False, help_text='Designates that this user has all permissions without explicitly assigning them.', verbose_name='superuser status')),
                ('first_name', models.CharField(blank=True, max_length=150, verbose_name='first name')),
                ('last_name', models.CharField(blank=True, max_length=150, verbose_name='last name')),
                ('is_staff', models.BooleanField(default=False, help_text='Designates whether the user can log into this admin site.', verbose_name='staff status')),
                ('is_active', models.BooleanField(default=True, help_text='Designates whether this user should be treated as active. Unselect this instead of deleting accounts.', verbose_name='active')),
                ('date_joined', models.DateTimeField(default=django.utils.timezone.now, verbose_name='date joined')),
                ('phone', models.CharField(max_length=11, unique=True, verbose_name='Phone')),
                ('email', models.EmailField(max_length=254, verbose_name='email address')),
                ('groups', models.ManyToManyField(blank=True, help_text='The groups this user belongs to. A user will get all permissions granted to each of their groups.', related_name='user_set', related_query_name='user', to='auth.group', verbose_name='groups')),
                ('user_permissions', models.ManyToManyField(blank=True, help_text='Specific permissions for this user.', related_name='user_set', related_query_name='user', to='auth.permission', verbose_name='user permissions')),
            ],
            options={
                'verbose_name': 'user',
                'verbose_name_plural': ' users',
            },
            managers=[
                ('objects', user.manager.UserManager()),
            ],
        ),
        migrations.CreateModel(
            name='OTP',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('code', models.CharField(help_text='code', max_length=11, unique=True, verbose_name='code')),
                ('exp_time', models.DateTimeField(help_text='Time out', verbose_name='exp_time')),
                ('exp_time_error_send', models.DateTimeField(blank=True, help_text='Time to resend the code', null=True, verbose_name='exp_time_error_send')),
                ('exp_time_error_verified', models.DateTimeField(blank=True, help_text='Time to code confirmation', null=True, verbose_name='exp_time_error_verified')),
                ('number_error_3time', models.PositiveIntegerField(blank=True, help_text='number of time enter the code', null=True, verbose_name='number_error_3time')),
                ('number_error_5time', models.PositiveIntegerField(blank=True, help_text='number of time send the code', null=True, verbose_name='number_error_5time')),
                ('type', models.IntegerField(choices=[(1, 'REGISTER'), (2, 'LOGIN')], help_text='type', verbose_name='type')),
                ('user', models.ForeignKey(help_text='user', on_delete=django.db.models.deletion.PROTECT, related_name='otp_user', to=settings.AUTH_USER_MODEL, verbose_name='user')),
            ],
        ),
    ]
