# Generated by Django 4.1 on 2022-08-24 08:41

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='OTP',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('code', models.CharField(help_text='code', max_length=11, unique=True, verbose_name='code')),
                ('exp_time', models.DateTimeField(help_text='Time out', verbose_name='exp_time')),
                ('exp_time_error_send', models.DateTimeField(blank=True, help_text='Time to resend the code', null=True, verbose_name='exp_time_error_send')),
                ('exp_time_error_verified', models.DateTimeField(blank=True, help_text='Time to code confirmation', null=True, verbose_name='exp_time_error_verified')),
                ('number_error_3time', models.PositiveIntegerField(blank=True, help_text='number of time enter the code', null=True, verbose_name='number_error_3time')),
                ('number_error_5time', models.PositiveIntegerField(blank=True, help_text='number of time send the code', null=True, verbose_name='number_error_5time')),
                ('type', models.IntegerField(choices=[(1, 'REGISTER'), (2, 'LOGIN')], help_text='type', verbose_name='type')),
                ('user', models.ForeignKey(help_text='user', on_delete=django.db.models.deletion.PROTECT, related_name='otp_user', to=settings.AUTH_USER_MODEL, verbose_name='user')),
            ],
        ),
    ]
