# Generated by Django 4.1 on 2022-09-10 07:53

from django.db import migrations, models
import django.db.models.deletion
import handout.models.handout


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Category',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=100, unique=True, verbose_name='Title')),
                ('logo', models.ImageField(blank=True, null=True, upload_to='storage/logo', verbose_name='Logo')),
            ],
            options={
                'verbose_name': 'category',
                'verbose_name_plural': 'categorys',
                'ordering': ('title',),
            },
        ),
        migrations.CreateModel(
            name='Course',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255, verbose_name='Title')),
                ('logo', models.ImageField(blank=True, null=True, upload_to='storage/logo', verbose_name='Logo')),
            ],
            options={
                'verbose_name': 'course',
                'verbose_name_plural': 'courses',
                'ordering': ('title',),
            },
        ),
        migrations.CreateModel(
            name='Major',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255, unique=True, verbose_name='Title')),
            ],
            options={
                'verbose_name': 'Major',
                'verbose_name_plural': 'Majors',
                'ordering': ('title',),
            },
        ),
        migrations.CreateModel(
            name='Professor',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255, unique=True, verbose_name='Name')),
                ('picture', models.ImageField(blank=True, null=True, upload_to='storage/picture', verbose_name='Picture')),
                ('title', models.CharField(choices=[('دکتر', 'دکتر'), ('مهندس', 'مهندس'), ('آقای', 'آقای'), ('خانم', 'خانم')], default='دکتر', max_length=20, verbose_name='Title')),
            ],
            options={
                'verbose_name': 'Professor',
                'verbose_name_plural': 'Professors',
                'ordering': ('name',),
            },
        ),
        migrations.CreateModel(
            name='UniversityType',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255, unique=True, verbose_name='Title')),
            ],
            options={
                'verbose_name': 'University Type',
                'verbose_name_plural': 'Universitie Types',
                'ordering': ('title',),
            },
        ),
        migrations.CreateModel(
            name='University',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255, unique=True, verbose_name='Name')),
                ('logo', models.ImageField(blank=True, null=True, upload_to='storage/logo', verbose_name='Logo')),
                ('type', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='handout.universitytype', verbose_name='Type')),
            ],
            options={
                'verbose_name': 'University',
                'verbose_name_plural': 'Universities',
                'ordering': ('name',),
            },
        ),
        migrations.CreateModel(
            name='Minor',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255, unique=True, verbose_name='Title')),
                ('major', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='handout.major', verbose_name='Major')),
            ],
            options={
                'verbose_name': 'Minor',
                'verbose_name_plural': 'Minors',
                'ordering': ('title',),
            },
        ),
        migrations.CreateModel(
            name='Handout',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('file', models.FileField(upload_to=handout.models.handout.get_file_path, verbose_name='File')),
                ('year', models.IntegerField(blank=True, null=True, verbose_name='Year')),
                ('author', models.CharField(blank=True, max_length=255, null=True, verbose_name='Author')),
                ('description', models.TextField(blank=True, null=True, verbose_name='Description')),
                ('upload_datetime', models.DateTimeField(auto_now_add=True, verbose_name='Upload Datetime')),
                ('title', models.CharField(blank=True, max_length=255, null=True, verbose_name='Title')),
                ('add_datetime', models.DateTimeField(auto_now_add=True, verbose_name='Add Datetime')),
                ('modify_datetime', models.DateTimeField(auto_now=True, verbose_name='Modify Datetime')),
                ('logo', models.ImageField(blank=True, null=True, upload_to='storage/logo', verbose_name='Logo')),
                ('is_processed', models.BooleanField(default=False, verbose_name='Is Processed')),
                ('category', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='category', to='handout.category', verbose_name='Category')),
                ('course', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='handout.course', verbose_name='Course')),
                ('professor', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='handout.professor', verbose_name='Professor')),
                ('university', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='handout.university', verbose_name='University')),
            ],
            options={
                'verbose_name': 'handout',
                'verbose_name_plural': 'handouts',
                'ordering': ('-upload_datetime',),
            },
        ),
        migrations.AddField(
            model_name='course',
            name='minor',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='handout.minor', verbose_name='Minor'),
        ),
        migrations.AlterUniqueTogether(
            name='course',
            unique_together={('minor', 'title')},
        ),
    ]
