# Generated by Django 4.1 on 2022-09-03 06:42

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('handout', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='handout',
            name='category',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='category', to='handout.category', verbose_name='Category'),
        ),
    ]
