# Generated by Django 4.1 on 2022-09-09 09:37

from django.db import migrations
import django_jalali.db.models


class Migration(migrations.Migration):

    dependencies = [
        ('handout', '0002_alter_handout_category'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='category',
            options={'ordering': ('title',), 'verbose_name': 'category', 'verbose_name_plural': 'categorys'},
        ),
        migrations.AlterModelOptions(
            name='course',
            options={'ordering': ('title',), 'verbose_name': 'course', 'verbose_name_plural': 'courses'},
        ),
        migrations.AlterModelOptions(
            name='handout',
            options={'ordering': ('-upload_datetime',), 'verbose_name': 'handout', 'verbose_name_plural': 'handouts'},
        ),
        migrations.AlterField(
            model_name='handout',
            name='add_datetime',
            field=django_jalali.db.models.jDateTimeField(auto_now_add=True, verbose_name='Add Datetime'),
        ),
        migrations.AlterField(
            model_name='handout',
            name='modify_datetime',
            field=django_jalali.db.models.jDateTimeField(auto_now=True, verbose_name='Modify Datetime'),
        ),
        migrations.AlterField(
            model_name='handout',
            name='upload_datetime',
            field=django_jalali.db.models.jDateTimeField(auto_now_add=True, verbose_name='Upload Datetime'),
        ),
    ]
