# Generated by Django 4.1 on 2022-09-09 12:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('handout', '0003_alter_category_options_alter_course_options_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='handout',
            name='add_datetime',
            field=models.DateTimeField(auto_now_add=True, verbose_name='Add Datetime'),
        ),
        migrations.AlterField(
            model_name='handout',
            name='modify_datetime',
            field=models.DateTimeField(auto_now=True, verbose_name='Modify Datetime'),
        ),
        migrations.AlterField(
            model_name='handout',
            name='upload_datetime',
            field=models.DateTimeField(auto_now_add=True, verbose_name='Upload Datetime'),
        ),
    ]
